name: TA-to-Sheets

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip tooling
        run: |
          python -m pip install --upgrade "pip<24" "setuptools<70" wheel

      - name: Install dependencies
        run: |
          pip install --no-cache-dir --upgrade --force-reinstall -r requirements.txt

      - name: Write service account key
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          echo "$GOOGLE_SERVICE_ACCOUNT_JSON" > $RUNNER_TEMP/sa.json

      - name: Run script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/sa.json
          FINMIND_TOKEN: ${{ secrets.FINMIND_TOKEN }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          python src/main.py
