name: TA-to-Sheets

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Run mode (dev=寫 _test；prod=寫正式)"
        type: choice
        required: true
        options: [dev, prod]
        default: dev

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      # 這兩個環境變數會被 src/main.py 使用
      MODE: ${{ github.event.inputs.mode || 'dev' }}
      GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

    steps:
      - name: Checkout (use selected branch)
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          echo "MODE=${MODE}"
          python src/main.py
