name: TA-to-Sheets-Test

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Select mode'
        required: true
        options: [dev, prod]
        default: dev

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      MODE: ${{ github.event.inputs.mode || 'dev' }}
      GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      SHEET_ID: ${{ secrets.SHEET_ID }}
    steps:
      - name: Checkout (test branch)
        uses: actions/checkout@v4
        with:
          ref: test

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Echo mode
        run: echo "MODE=${MODE}"

      - name: Run main.py (test)
        run: python src/main.py
