name: TA-to-Sheets-Prod

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      MODE: prod
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
      SHEET_ID: ${{ secrets.SHEET_ID }}
    steps:
      - name: Checkout (main)
        uses: actions/checkout@v4
        with:
            ref: main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py (prod)
        run: python src/main.py
