name: TW-Stock King's Analysis v5.0 (Self-Reliant)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Core Dependencies
      run: |
        python -m pip install --upgrade pip
        # --- 關鍵修正：徹底移除 pandas-ta，只安裝最核心、最穩定的函式庫 ---
        pip install pandas numpy yfinance gspread google-auth-oauthlib google-api-python-client pytz retrying requests

    - name: Run The King's Analysis (TW)
      env:
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        SHEET_ID: ${{ secrets.SHEET_ID }}
        FINMIND_TOKEN: ${{ secrets.FINMIND_TOKEN }}
      run: python -u main.py
